using System;
using System.Diagnostics;
using System.IO;
using Libptx.Common;
using Libptx.Common.Types.Pointers;
using Libptx.Expressions;
using Type=Libptx.Common.Types.Type;

namespace Libptx.Statements
{
    [DebuggerNonUserCode]
    public class Label : Atom, Expression, Statement
    {
        public String Name { get; set; }
        public Type Type { get { return typeof(Bmk); } }

        protected override void CustomValidate(Module ctx)
        {
            // if name is null, it'll be autogenerated by Entry::Validate
            if (Name != null) Name.ValidateName();
            // uniqueness of names is validated by Entry
        }

        protected override void RenderAsPtx(TextWriter writer)
        {
            writer.Write(Name);
        }
    }
}